package com.bnta.dark_heresy_character_sheet.models;

public enum WeaponAttributes {
    ACCURATE,
    BALANCED,
    BLAST,
    DEFENSIVE,
    FLAME,
    FLEXIBLE,
    INACCURATE,
    OVERHEATS,
    POWER_FIELD,
    PRIMITIVE,
    RECHARGE,
    SCATTER,
    SHOCKING,
    SMOKE,
    SNARE,
    TEARING,
    TOXIC,
    UNBALANCED,
    UNRELIABLE,
    UNSTABLE,
    UNWIELDY,
}
